import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from "sonner";
import { TanstackQueryProvider } from "./providers";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Project Mgmt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackQueryProvider>
          <div className="min-h-screen flex flex-col justify-between">
            <Navbar />
            <main className="p-5 flex-1 max-w-7xl w-full mx-auto">
              {children}
            </main>
            <footer className="py-4 px-8 flex flex-wrap md:flex-nowrap gap-2 justify-between">
              <h1>All copyright reserved ©️ 2024</h1>
              <h2>
                For any queries, contact{" "}
                <span className="font-semibold">
                  dipanshu.torawane@vit.edu.in
                </span>
              </h2>
            </footer>
          </div>
          <Toaster richColors />
          <ReactQueryDevtools initialIsOpen={false} />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
